name: Backend Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun.js
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
        working-directory: backend

      - name: Set up .env file
        run: |
          echo "DB_CONN_STRING=${{ secrets.DB_CONN_STRING }}" > backend/.env
        env:
          DB_CONN_STRING: ${{ secrets.DB_CONN_STRING }}

      - name: Run unit tests
        run: bun run test
        working-directory: backend
